# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMobDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdMobDemo

pod 'Google-Mobile-Ads-SDK' 

  target 'AdMobDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdMobDemoUITests' do
    # Pods for testing
  end

end
